---

 # Test
  tasks:

    get_google_creds:
      run: True

      vars: 

      log:

    environmental_vars:
      run: True

      criteria_sheet_ids: {input_list: '1KuwVVLfoj0JrlV0fpma9LHEOgTNZXvH33vQCA1JxFQo',dnn: '178avLfJ_XlwdRk_7JR0nho6vCIqDnAqMjFYHs78ZVgk' ,cities: '1SDr2etHonIrOhEZMPEwD7riMUF_AlMuRiG8ZtgB6PB8',zip: '17Ymbqvjt4SAQD85ofK5dfKdFxQX4H6sEU7R90BVRrqk'}

      output_sheet_ids: {output: null}

      output_folder_id: '1EU57r3Le1w6FI-eIuGOucQitxKvsn51X'
      
      sheet_meta: {}

      batch_size: 500

      sep: ''

      suffixes: {json_suffix: "json", csv_suffix: "csv"}

      date: {}

      dfs: {}

      vars: {master_chunksize: 500}

      file_names: {agent_data_raw: 'agent_data_raw', agent_data_mapped: 'agent_data_mapped'}

      directories: {dnn: 'dnn', cwd: '', log_directory: 'log', to_merge: 'to_merge\connecticut', merged_data: "merged_data", filted_data: "filtered_data", extracted_data: "extracted_data", mapped_data: "mapped_data", cities: 'cities'}
      
      log: {}

    confirm_folder_structure:
      run: False

      

      log: {}

    scrape_web_data_rew:
      input_list: {run: True, data_batch: []}

      city_criteria: {run: False, state: {'': []}}

      state_criteria: {run: False, list: []}

      run: False


    scrape_web_data_sheets:

      input_list: {run: True, data_batch: []}

      city_criteria: {run: False, state: {'': []}}

      state_criteria: {run: False, list: []}

      run: True

      vars: {master_chunksize: 500}

      log: {}


      vars: {master_chunksize: 500}

      log: {}

    scrape_web_data:
      run: False

      vars: {master_chunksize: 500}

      log: {}


    merge_data:
      run: False

      vars: {master_chunksize: 500} 

      log: {}

    filter_data:
      run: False

      vars: {master_chunksize: 500} 

      log: {}
 

    extract_agent_data:
      run: False

      vars: {master_chunksize: 500}

      log: {}

      
    map_data:
      vars: {master_chunksize: 500} 
      run: False
      log: {}
      directories: {input_directory: "new_subscribers", output_directory: "new_subscribers",
                    read_directory: 'master',
                    csv_log_directory: log,
                    json_dump_directory: log} 

      files: {output_extension: "csv",
              output_prefix: 'table',
              output_filename: "unsubscribers",
              json_dump_filename: dump.json,
              csv_log_filename: log.log}


    unsubscribe:
     vars: {master_chunksize: 500} 
     run: False
     log: {}

     directories: {input_directory: "unsubscribers", output_directory: "unsubscribers",
                    read_directory: 'single_merge',
                    csv_log_directory: log,
                    json_dump_directory: log} 

     files: {output_extension: "csv",
              output_prefix: 'table',
              output_filename: "unsubscribers",
              json_dump_filename: dump.json,
              csv_log_filename: log.log}

    create_POC_table:
      run: False 

      vars: {master_chunksize: 500}

      log: {}

      directories: {input_directory: "new_contacts", output_directory: "point_of_contact",
                    read_directory: 'master',
                    csv_log_directory: log,
                    json_dump_directory: log}

      files: {output_extension: "csv",
              output_prefix: 'table',
              output_filename: "point_of_contacts",
              json_dump_filename: dump.json,
              csv_log_filename: log.log}
    
    create_company_table:
      run: False
      vars: {master_chunksize: 500}
      log: {}
      directories: {input_directory: "new_contacts", output_directory: "company_table",
                    read_directory: 'master',
                    csv_log_directory: log,
                    json_dump_directory: log}
      files: {output_extension: "csv",
              output_prefix: 'table',
              output_filename: "companies",
              json_dump_filename: dump.json,
              csv_log_filename: log.log}



      

      
      

      

      
 
...